name: graduation___part1
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.4.3 # Updated to match the Dart SDK version

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  provider: ^6.1.2
  no_screenshot: ^0.3.1
  record: ^5.2.1
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  fl_chart: ^0.55.2
  intl: ^0.19.0
  url_launcher: ^6.3.1
  flutter_inappwebview: ^6.0.0
  video_player: ^2.9.3
  dio: ^5.8.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.2.0
  image_picker: ^1.1.2
  connectivity_plus: ^6.1.3
  signalr_core: ^1.1.2
  animate_do: ^4.2.0
  local_auth: ^2.3.0
  audioplayers: ^6.4.0
  carousel_slider: ^5.0.0
  shared_preferences: ^2.0.6 # Compatible with Dart SDK >=3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700