name: graduation___part1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  animations: ^2.0.11
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  #camera: ^0.11.0
  carousel_slider: ^5.0.0
  connectivity_plus: ^6.0.1
  cookie_jar: ^4.0.8
  dio: ^5.7.0
  dio_cookie_manager: ^3.1.1
  fixnum: ^1.1.0
  fl_chart: ^0.69.2
  flutter_staggered_animations: ^1.1.1
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  json_annotation: ^4.9.0
  local_auth: ^2.3.0
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  video_player: ^2.9.2
  web_socket_channel: ^3.0.1
  no_screenshot: ^0.3.1
  webview_flutter: ^4.8.0
  dartz: ^0.10.1
  path_provider: ^2.1.1 # Add this line


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/informant.jpeg
    - assets/internet.jpeg
    - assets/login1.png