name: graduation___part1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  intl: ^0.19.0
  provider: ^6.1.2
  video_player: ^2.9.2
  assets:
    - assets/login.png
   # - assets/signup.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
