name: graduation___part1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.1.2
  video_player: ^2.9.2
  carousel_slider: ^5.0.0
  fl_chart: ^0.69.0
  image_picker: ^1.1.2
  animations: ^2.0.11
  google_fonts: ^6.2.1
  camera: ^0.11.0+2
  local_auth: ^2.1.8
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.3.3
  no_screenshot: ^0.3.1
  connectivity_plus: ^6.1.1
  url_launcher: ^6.3.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  web_socket_channel: ^3.0.1
  dio: ^5.7.0
  freezed_annotation: ^2.4.4
  bloc: ^8.1.4
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.6
  flutter_staggered_animations: ^1.1.1
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  dartz: ^0.10.1
  fixnum: ^1.1.0
  


flutter:
  uses-material-design: true
  assets:
    - assets/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
